name: Deploy Modul Siswa App to cPanel

on:
  push:
    branches:
      - main # Atau branch yang Anda gunakan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload to cPanel via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SFTP_HOSTNAME_SADE }}
        username: ${{ secrets.SFTP_USERNAME_SADE }}
        password: ${{ secrets.SFTP_PASSWORD_SADE }}
        local-dir: ./dist/spa/
        server-dir: /
        protocol: sftp
        passive: true
        timeout: 60000 # Timeout in milliseconds
