name: Deploy Modul Siswa App to cPanel

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOSTNAME_SADE }}
        username: ${{ secrets.FTP_USERNAME_SADE }}
        password: ${{ secrets.FTP_PASSWORD_SADE }}
        local-dir: ./dist/spa/
        server-dir: / 
